# Generated by Django 3.2.21 on 2024-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='null', max_length=100)),
                ('last_name', models.CharField(default='null', max_length=100)),
                ('about', models.CharField(default='null', max_length=200)),
                ('mobile_number', models.CharField(default='null', max_length=20)),
                ('profile_img', models.ImageField(null=True, upload_to='teacher_profile_imgs/')),
                ('facebook_url', models.URLField(null=True)),
                ('twitter_url', models.URLField(null=True)),
                ('instagram_url', models.URLField(null=True)),
                ('website_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': '1. Instructor',
            },
        ),
    ]
