# Generated by Django 3.2.21 on 2024-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='facebook_url',
            field=models.URLField(blank='', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram_url',
            field=models.URLField(blank='', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='twitter_url',
            field=models.URLField(blank='', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='website_url',
            field=models.URLField(blank='', null=True),
        ),
    ]
