# Generated by Django 3.2.21 on 2024-11-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20241120_1154'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interested_categories',
            field=models.ManyToManyField(to='main.Course_category'),
        ),
        migrations.AddField(
            model_name='studentcourseenrolled',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.course'),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='studentfavoritecourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='studentnoteprogress',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.note'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnoteprogress',
            unique_together={('student', 'note')},
        ),
        migrations.AlterUniqueTogether(
            name='studenttopicprogress',
            unique_together={('student', 'topic')},
        ),
    ]
