# Generated by Django 3.2.21 on 2024-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_imgs/'),
        ),
    ]
