# Generated by Django 3.2.21 on 2024-12-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20241209_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('result', 'question')},
        ),
    ]
